- name: Install php5-fpm and dependencies
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-fpm
    - php5-cli
    - php5-mysql
    - php5-mcrypt

#Needed for PHP 5.4
- name: Set permissions on socket - owner
  lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;listen.owner' line='listen.owner = {{ vagrant_user }}'"
  notify: restart php5-fpm

- name: Set permissions on socket - group
  lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;listen.group' line='listen.group = {{ vagrant_user }}'"
  notify: restart php5-fpm

- name: Set permissions on socket - mode
  lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;listen.mode' line='listen.mode = 0660'"
  notify: restart php5-fpm

- name: ensure timezone is set in fpm php.ini
  lineinfile: dest=/etc/php5/fpm/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ timezone }}'
