---
- hosts: all
  sudo: true
  vars_files:
    - vars/common.yml
    - vars/php.yml
    - vars/nginx.yml
    - vars/mysql.yml
  roles:
    - init
    - php5-cli
    - nginx
    - php5-fpm
    - xdebug
    - mysql
    - composer
    - phpcommon
    - symfony
    - app
